### PR TITLE
Add JS support

### PR DESCRIPTION
**Pull request by adelbertc**
May or may not have been copy/pasta-ed + modified from the Cats build

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks! Will merge when green.

**Comment by adelbertc** [comment]
I'm trying to figure out how test are passing.. they shouldn't be passing in JS.. is the JS build not running or something?

**Comment by travisbrown** [comment]
@adelbertc Oh, weird. I'm not sure—I also just cargo-cult all this Scala.js stuff.

**Comment by adelbertc** [comment]
Oh I guess because it wasn't under `shared` so it just.. ran it for JVM.. somehow? http://www.scala-js.org/doc/project/cross-build.html

**Comment by travisbrown** [comment]
You don't want `shared` with `CrossType.Pure`, right?

**Pull request merged**
